// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQYV1WpxP7RRKq_2a1puwK4YJIEvuVTBs',
    appId: '1:408359940546:web:6d338f29125a60ebd8265b',
    messagingSenderId: '408359940546',
    projectId: 'wep-uas',
    authDomain: 'wep-uas.firebaseapp.com',
    storageBucket: 'wep-uas.appspot.com',
    measurementId: 'G-PXCPXY1DJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoAmd6DOKVCHbvPTcIS6SXRlDXvv_sD8M',
    appId: '1:408359940546:android:2aab034d03d9ab60d8265b',
    messagingSenderId: '408359940546',
    projectId: 'wep-uas',
    storageBucket: 'wep-uas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr62eK5pOsn4bhdWqGD6zid1rmue0elf0',
    appId: '1:408359940546:ios:22cb2aafddddecb5d8265b',
    messagingSenderId: '408359940546',
    projectId: 'wep-uas',
    storageBucket: 'wep-uas.appspot.com',
    iosBundleId: 'com.example.ecommerceFirebase',
  );
}
